runtime: python-3.11

# Environment variables for Azure App Service
env_variables:
  GEMINI_API_KEY_1: "your_api_key_1_here"
  GEMINI_API_KEY_2: "your_api_key_2_here"
  GEMINI_API_KEY_3: "your_api_key_3_here"
  GEMINI_API_KEY_4: "your_api_key_4_here"

# Health check endpoint
health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  initial_delay_sec: 30
